language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t dice/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dice/react-test npm test

after_success:
  - docker build -t 040130102/multi-client ./client
  - docker build -t 040130102/multi-nginx ./nginx
  - docker build -t 040130102/multi-server ./server
  - docker build -t 040130102/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin docker.io
  # Take those images and push them to docker hub
  - docker push 040130102/multi-client
  - docker push 040130102/multi-nginx
  - docker push 040130102/multi-server
  - docker push 040130102/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-west-2-656107153223"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY